### ISSUE TITLE
Little Sir Echo crashes on startup

### ISSUE THREAD

**Issue by leggewie** [kaputnikGo/LittleSirEcho#4]
* Device OS and version: Android 6.0.1
* Device model/manufacturer: Alcatel Pop 4
* F-Droid version: 1.3

Little Sir Echo simply crashes on startup ("Unfortunately, Little Sir Echo has stopped.").

**Comment by kaputnikGo** [comment]
It won't run on Android 6.x due to the changes made to the Android API. There are alternatives on F-Droid.

**Comment by leggewie** [comment]
Can you name those alternatives more precisely? Thank you.

**Comment by kaputnikGo** [comment]
Searching found these:
https://f-droid.org/en/packages/com.bleyl.recurrence/
https://f-droid.org/en/packages/com.app.missednotificationsreminder/

your results may vary depending on how your phone behaves and the permissions required.

**Comment by leggewie** [comment]
Thank you.

I am not that familiar with Android packaging.  Is it possible to specify a minimum Android version or else refuse to install the app?  That would be useful.
